@Gateway_HostAddress = http://localhost:8080

POST {{Gateway_HostAddress}}/containers/
Accept: application/json
Content-Type: application/json

{
  "container": "users",
  "partitionKeyPath": "city"
}

###

GET {{Gateway_HostAddress}}/containers/
Accept: application/json
Content-Type: application/json

###

POST {{Gateway_HostAddress}}/containers/users/query
Accept: application/json
Content-Type: application/json

{
  "Sql": "SELECT id, age FROM c WHERE city = 'Asolo'"
}

###

PUT {{Gateway_HostAddress}}/containers/users/documents
Accept: application/json
Content-Type: application/json

{
  "id": "matteo",
  "name": "Matteo",
  "city": "Asolo",
  "age": 30
}

###

GET {{Gateway_HostAddress}}/containers/users/documents/matteo1?partitionKeyValue=Asolo
Accept: application/json
